### ISSUE TITLE
Error when running yo aurora:extras, without having a .yo-rc.json file

### ISSUE THREAD

**Issue by fidelix** [Snugug/generator-aurora#1]
You're installing extras for your Aurora based Drupal theme.
http://drupal.org/project/aurora - http://snugug.github.io/Aurora/

[?] What options would you like to include? Gulp, Bower

undefined:7
((__t = ( projectSlug )) == null ? '' : __t) +
          ^
ReferenceError: projectSlug is not defined
    at eval (eval at template (/usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:7:11)
    at underscore [as _engine](/usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/util/engines.js:32:30)
    at engine (/usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
    at template (/usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
    at yeoman.generators.Base.extend.options (/usr/lib/node_modules/generator-aurora/extras/index.js:57:12)
    at /usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25

**Comment by Snugug** [comment]
What version of generator-aurora are you using?

**Comment by fidelix** [comment]
I ran npm install -g generator-aurora just yesterday night

**Comment by Snugug** [comment]
Please run  `npm view -g generator-aurora version`

**Comment by fidelix** [comment]
0.2.1

**Comment by zachharkey** [comment]
I'm getting the same error when I try to run `yo aurora:extras` after running `yo aurora`.

```
npm view -g generator-aurora version
0.2.2
```

Are we supposed to run `yo aurora:extras` from the same directory where we ran `yo aurora`? Or are we supposed to cd into our newly created aurora subtheme first? What exactly does `yo aurora:extras` install and where?

Full error message:

```
You're installing extras for your Aurora based Drupal theme.
http://drupal.org/project/aurora - http://snugug.github.io/Aurora/

[?] What options would you like to include? Gulp, Bower

undefined:7
((__t = ( projectSlug )) == null ? '' : __t) +
          ^
ReferenceError: projectSlug is not defined
    at eval (eval at template (/usr/local/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:7:11)
    at underscore [as _engine] (/usr/local/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/util/engines.js:32:30)
    at engine (/usr/local/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
    at template (/usr/local/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
    at yeoman.generators.Base.extend.options (/usr/local/lib/node_modules/generator-aurora/extras/index.js:57:12)
    at /usr/local/lib/node_modules/generator-aurora/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-aurora/node_modules/yeoman-generator/node_mod
```

**Comment by iamcarrico** [comment]
Do you have the .yo-rc.json file in your directory?

**Comment by jantoine1** [comment]
I ran into this error when running the command on an aurora sub-theme that was originally built using older tools (wasn't originally build using Yeoman). Rebuilding the theme from scratch and migrating my changes resolved this error for me.

**Comment by iamcarrico** [comment]
Currently, the generator requires you have the .yo-rc.json file, as it pulls your settings from there. I am going to edit this issue's title to add that feature.
